/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Source = {
  _id: string;
  _type: "source";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  publisher?: string;
  publishedAt?: string;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type NarrativeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "narrative";
};

export type SourceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "source";
};

export type Narrative = {
  _id: string;
  _type: "narrative";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  overview?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  countries?: Array<string>;
  parties?: Array<{
    name?: string;
    iso?: string;
    _type: "party";
    _key: string;
  }>;
  accentColor?: string;
  keywords?: Array<string>;
  relatedNarratives?: Array<
    {
      _key: string;
    } & NarrativeReference
  >;
  sources?: Array<
    {
      _key: string;
    } & SourceReference
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  introduction?: string;
  email?: string;
  enquiryLinks?: Array<{
    label?: string;
    subject?: string;
    _type: "enquiryLink";
    _key: string;
  }>;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  introduction?: string;
  body?: Array<{
    text?: string;
    _type: "paragraph";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Source
  | NarrativeReference
  | SourceReference
  | Narrative
  | Slug
  | ContactPage
  | AboutPage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../nara/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0] {    heading,    introduction,    "body": coalesce(body[]{_key, text}, [])  }
export type ABOUT_PAGE_QUERY_RESULT =
  | {
      heading: null;
      introduction: null;
      body:
        | Array<{
            _key: string;
            text: null;
          }>
        | Array<never>;
    }
  | {
      heading: string | null;
      introduction: string | null;
      body:
        | Array<{
            _key: string;
            text: string | null;
          }>
        | Array<never>;
    }
  | {
      heading: null;
      introduction: null;
      body: Array<never>;
    }
  | {
      heading: string | null;
      introduction: string | null;
      body: Array<never>;
    }
  | null;

// Source: ../nara/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_id == "contactPage"][0] {    heading,    introduction,    email,    "enquiryLinks": coalesce(enquiryLinks[]{_key, label, subject}, [])  }
export type CONTACT_PAGE_QUERY_RESULT =
  | {
      heading: null;
      introduction: null;
      email: null;
      enquiryLinks: Array<never>;
    }
  | {
      heading: string | null;
      introduction: string | null;
      email: null;
      enquiryLinks: Array<never>;
    }
  | {
      heading: string | null;
      introduction: string | null;
      email: string | null;
      enquiryLinks:
        | Array<{
            _key: string;
            label: string | null;
            subject: string | null;
          }>
        | Array<never>;
    }
  | null;

// Source: ../nara/sanity/queries.ts
// Variable: NARRATIVES_QUERY
// Query: *[_type == "narrative" && defined(slug.current)]  | order(name asc) {    _id,    "id": slug.current,    "slug": slug.current,    name,    "overview": coalesce(overview, ""),    "countries": coalesce(countries, []),    "parties": coalesce(parties[]{_key, name, iso}, []),    "accentColor": coalesce(accentColor, "#9B6B6B"),    "keywords": coalesce(keywords, []),    "relatedIds": coalesce(relatedNarratives[]->slug.current, []),    "sourceCount": count(sources)  }
export type NARRATIVES_QUERY_RESULT = Array<{
  _id: string;
  id: string | null;
  slug: string | null;
  name: string | null;
  overview: string | "";
  countries: Array<string> | Array<never>;
  parties:
    | Array<{
        _key: string;
        name: string | null;
        iso: string | null;
      }>
    | Array<never>;
  accentColor: string | "#9B6B6B";
  keywords: Array<string> | Array<never>;
  relatedIds: Array<never> | Array<string | null>;
  sourceCount: number | null;
}>;

// Source: ../nara/sanity/queries.ts
// Variable: NARRATIVE_BY_SLUG_QUERY
// Query: *[_type == "narrative" && slug.current == $slug][0] {    _id,    "id": slug.current,    "slug": slug.current,    name,    "overview": coalesce(overview, ""),    "countries": coalesce(countries, []),    "parties": coalesce(parties[]{_key, name, iso}, []),    "accentColor": coalesce(accentColor, "#9B6B6B"),    "keywords": coalesce(keywords, []),    "relatedIds": coalesce(relatedNarratives[]->slug.current, []),    "sourceCount": count(sources),    "related": coalesce(relatedNarratives[]->{      _id,      "id": slug.current,      "slug": slug.current,      name,      "overview": coalesce(overview, ""),      "countries": coalesce(countries, []),      "parties": coalesce(parties[]{_key, name, iso}, []),      "accentColor": coalesce(accentColor, "#9B6B6B"),      "keywords": coalesce(keywords, []),      "relatedIds": coalesce(relatedNarratives[]->slug.current, []),      "sourceCount": count(sources)    }, [])  }
export type NARRATIVE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  id: string | null;
  slug: string | null;
  name: string | null;
  overview: string | "";
  countries: Array<string> | Array<never>;
  parties:
    | Array<{
        _key: string;
        name: string | null;
        iso: string | null;
      }>
    | Array<never>;
  accentColor: string | "#9B6B6B";
  keywords: Array<string> | Array<never>;
  relatedIds: Array<never> | Array<string | null>;
  sourceCount: number | null;
  related:
    | Array<{
        _id: string;
        id: string | null;
        slug: string | null;
        name: string | null;
        overview: string | "";
        countries: Array<string> | Array<never>;
        parties:
          | Array<{
              _key: string;
              name: string | null;
              iso: string | null;
            }>
          | Array<never>;
        accentColor: string | "#9B6B6B";
        keywords: Array<string> | Array<never>;
        relatedIds: Array<never> | Array<string | null>;
        sourceCount: number | null;
      }>
    | Array<never>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "aboutPage"][0] {\n    heading,\n    introduction,\n    "body": coalesce(body[]{_key, text}, [])\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_id == "contactPage"][0] {\n    heading,\n    introduction,\n    email,\n    "enquiryLinks": coalesce(enquiryLinks[]{_key, label, subject}, [])\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[_type == "narrative" && defined(slug.current)]\n  | order(name asc) {\n    _id,\n    "id": slug.current,\n    "slug": slug.current,\n    name,\n    "overview": coalesce(overview, ""),\n    "countries": coalesce(countries, []),\n    "parties": coalesce(parties[]{_key, name, iso}, []),\n    "accentColor": coalesce(accentColor, "#9B6B6B"),\n    "keywords": coalesce(keywords, []),\n    "relatedIds": coalesce(relatedNarratives[]->slug.current, []),\n    "sourceCount": count(sources)\n  }\n': NARRATIVES_QUERY_RESULT;
    '\n  *[_type == "narrative" && slug.current == $slug][0] {\n    _id,\n    "id": slug.current,\n    "slug": slug.current,\n    name,\n    "overview": coalesce(overview, ""),\n    "countries": coalesce(countries, []),\n    "parties": coalesce(parties[]{_key, name, iso}, []),\n    "accentColor": coalesce(accentColor, "#9B6B6B"),\n    "keywords": coalesce(keywords, []),\n    "relatedIds": coalesce(relatedNarratives[]->slug.current, []),\n    "sourceCount": count(sources),\n    "related": coalesce(relatedNarratives[]->{\n      _id,\n      "id": slug.current,\n      "slug": slug.current,\n      name,\n      "overview": coalesce(overview, ""),\n      "countries": coalesce(countries, []),\n      "parties": coalesce(parties[]{_key, name, iso}, []),\n      "accentColor": coalesce(accentColor, "#9B6B6B"),\n      "keywords": coalesce(keywords, []),\n      "relatedIds": coalesce(relatedNarratives[]->slug.current, []),\n      "sourceCount": count(sources)\n    }, [])\n  }\n': NARRATIVE_BY_SLUG_QUERY_RESULT;
  }
}
