import type { Narrative, NarrativeCountry, NarrativeParty } from "./types";

function nc(iso: string, strength: number): NarrativeCountry {
  return { iso, strength };
}

function pp(name: string, iso: string): NarrativeParty {
  return { name, iso };
}

export const narratives: Narrative[] = [
  {
    id: "foreign-agent",
    slug: "foreign-agent",
    name: "Foreign Agent",
    category: "State Control",
    overview:
      "A legal and rhetorical frame used to discredit independent media, NGOs, and civil society by labelling them as instruments of foreign influence. Originating in post-Soviet legislation, the narrative has diffused across Central Europe and the Caucasus as governments tighten information controls.",
    countries: [
      nc("RU", 1),
      nc("BY", 0.9),
      nc("HU", 0.65),
      nc("GE", 0.65),
      nc("KZ", 0.85),
      nc("AZ", 0.60),
      nc("TR", 0.50),
    ],
    parties: [
      pp("United Russia", "RU"),
      pp("Belaya Rus", "BY"),
      pp("Fidesz", "HU"),
      pp("Georgian Dream", "GE"),
      pp("Amanat", "KZ"),
      pp("New Azerbaijan Party", "AZ"),
      pp("Justice and Development Party (AKP)", "TR"),
    ],
    accentColor: "#9B6B6B",
    timeline: [
      { year: 2012, label: "Russia adopts foreign-agent law targeting NGOs" },
      { year: 2017, label: "Designation extended to media outlets" },
      { year: 2021, label: "Hungary introduces 'foreign-funded NGOs' registry" },
      { year: 2023, label: "Georgia debates similar legislation amid protests" },
    ],
    actors: [
      "State Duma",
      "Roskomnadzor",
      "Fidesz parliamentary bloc",
      "Georgian Dream coalition",
    ],
    keywords: [
      "foreign influence",
      "NGO",
      "media registration",
      "national security",
      "sovereignty",
    ],
    relatedIds: ["liberal-dictatorship", "anti-west", "sovereignty"],
    yearFrom: 2012,
    yearTo: 2024,
    sourceCount: 7,
  },
  {
    id: "sovereignty",
    slug: "sovereignty",
    name: "Sovereignty",
    category: "Populism",
    overview:
      "A populist discourse asserting national self-determination against supranational institutions, migration policy, and perceived external interference. Deployed across the political spectrum to legitimise unilateral action and resist EU or NATO policy coordination.",
    countries: [
      nc("PL", 0.75),
      nc("HU", 0.85),
      nc("SK", 0.7),
      nc("CZ", 0.55),
      nc("IT", 0.5),
      nc("FR", 0.45),
      nc("GB", 0.8),
    ],
    parties: [
      pp("Law and Justice (PiS)", "PL"),
      pp("Fidesz", "HU"),
      pp("Smer – Social Democracy", "SK"),
      pp("Freedom and Direct Democracy (SPD)", "CZ"),
      pp("Brothers of Italy", "IT"),
      pp("National Rally", "FR"),
      pp("Reform UK", "GB"),
    ],
    accentColor: "#C4A265",
    timeline: [
      { year: 2016, label: "Brexit referendum frames sovereignty as core issue" },
      { year: 2018, label: "Visegrád bloc challenges EU migration quotas" },
      { year: 2020, label: "Rule-of-law disputes intensify in Poland and Hungary" },
      { year: 2023, label: "Sovereignty summits proliferate among illiberal leaders" },
    ],
    actors: [
      "Visegrád Group governments",
      "National conservative parties",
      "Eurosceptic media ecosystems",
      "Brussels institutions",
    ],
    keywords: [
      "national sovereignty",
      "Brussels",
      "self-determination",
      "subsidiarity",
      "illiberal democracy",
    ],
    relatedIds: ["national-identity", "anti-west", "traditional-values"],
    yearFrom: 2016,
    yearTo: 2024,
    sourceCount: 7,
  },
  {
    id: "liberal-dictatorship",
    slug: "liberal-dictatorship",
    name: "Liberal Dictatorship",
    category: "Anti-Democracy",
    overview:
      "A counter-narrative portraying liberal democratic norms — minority rights, judicial independence, press freedom — as authoritarian impositions by elites. Used to delegitimise opposition, courts, and civil society as undemocratic while consolidating executive power.",
    countries: [
      nc("RU", 1),
      nc("BY", 0.85),
      nc("HU", 0.8),
      nc("PL", 0.75),
      nc("SK", 0.55),
      nc("RS", 0.5),
    ],
    parties: [
      pp("United Russia", "RU"),
      pp("Belaya Rus", "BY"),
      pp("Fidesz", "HU"),
      pp("Law and Justice (PiS)", "PL"),
      pp("Smer – Social Democracy", "SK"),
      pp("Serbian Progressive Party", "RS"),
    ],
    accentColor: "#9B6B6B",
    timeline: [
      { year: 2014, label: "Term gains traction in Russian state media" },
      { year: 2018, label: "Orbán invokes 'liberal empire' in campaign rhetoric" },
      { year: 2020, label: "Polish public media adopts anti-liberal framing" },
      { year: 2023, label: "Serbian tabloids deploy frame against EU accession critics" },
    ],
    actors: [
      "State-aligned broadcasters",
      "PiS and Fidesz communication offices",
      "Orthodox Church media",
      "Pro-government think tanks",
    ],
    keywords: [
      "liberal dictatorship",
      "gender ideology",
      "rule of law",
      "elite capture",
      "majoritarianism",
    ],
    relatedIds: ["traditional-values", "foreign-agent", "sovereignty"],
    yearFrom: 2014,
    yearTo: 2024,
    sourceCount: 6,
  },
  {
    id: "traditional-values",
    slug: "traditional-values",
    name: "Traditional Values",
    category: "Culture War",
    overview:
      "A civilisational narrative positioning conservative social norms — family, religion, national heritage — against perceived Western liberal decadence. Central to Russia's soft-power diplomacy and replicated by allied movements across Eastern and Southern Europe.",
    countries: [
      nc("RU", 1),
      nc("HU", 0.85),
      nc("PL", 0.75),
      nc("RO", 0.55),
      nc("RS", 0.6),
      nc("SK", 0.5),
      nc("GE", 0.45),
      nc("TR", 0.5),
    ],
    parties: [
      pp("United Russia", "RU"),
      pp("Fidesz", "HU"),
      pp("Law and Justice (PiS)", "PL"),
      pp("Alliance for the Union of Romanians (AUR)", "RO"),
      pp("Serbian Progressive Party", "RS"),
      pp("Slovak National Party", "SK"),
      pp("Georgian Dream", "GE"),
      pp("Justice and Development Party (AKP)", "TR"),
    ],
    accentColor: "#C4A265",
    timeline: [
      { year: 2013, label: "Russia passes 'gay propaganda' law" },
      { year: 2019, label: "Budapest hosts World Family Congress" },
      { year: 2021, label: "Polish 'LGBT-free zones' controversy" },
      { year: 2023, label: "Georgia adopts foreign-agent law amid values rhetoric" },
    ],
    actors: [
      "Russian Orthodox Church",
      "World Congress of Families network",
      "National conservative parties",
      "Pro-family NGOs",
    ],
    keywords: [
      "traditional values",
      "family",
      "Christian heritage",
      "LGBT",
      "civilisation",
    ],
    relatedIds: ["liberal-dictatorship", "sovereignty", "national-identity"],
    yearFrom: 2013,
    yearTo: 2024,
    sourceCount: 8,
  },
  {
    id: "great-replacement",
    slug: "great-replacement",
    name: "Great Replacement",
    category: "Extremism",
    overview:
      "A conspiratorial narrative claiming deliberate demographic replacement of native European populations through migration and low birth rates. Rooted in far-right theory, it has entered mainstream political discourse and motivated violence across Western Europe.",
    countries: [
      nc("FR", 0.85),
      nc("DE", 0.55),
      nc("IT", 0.65),
      nc("HU", 0.75),
      nc("PL", 0.7),
      nc("AT", 0.6),
      nc("BE", 0.5),
      nc("SE", 0.45),
      nc("NL", 0.4),
    ],
    parties: [
      pp("National Rally", "FR"),
      pp("Alternative for Germany (AfD)", "DE"),
      pp("League", "IT"),
      pp("Fidesz", "HU"),
      pp("Confederation", "PL"),
      pp("Freedom Party of Austria (FPÖ)", "AT"),
      pp("Vlaams Belang", "BE"),
      pp("Sweden Democrats", "SE"),
      pp("Party for Freedom (PVV)", "NL"),
    ],
    accentColor: "#9B6B6B",
    timeline: [
      { year: 2011, label: "Renaud Camus publishes replacement thesis" },
      { year: 2017, label: "Marine Le Pen mainstreams demographic anxiety" },
      { year: 2019, label: "Christchurch manifesto cites replacement theory" },
      { year: 2023, label: "EU Parliament debates conspiracy in plenary" },
    ],
    actors: [
      "Identitarian movements",
      "Far-right parties (RN, AfD, FdI)",
      "Alternative media networks",
      "Online conspiracy communities",
    ],
    keywords: [
      "great replacement",
      "demographic change",
      "migration",
      "Islamisation",
      "white genocide",
    ],
    relatedIds: ["national-identity", "global-elites", "sovereignty"],
    yearFrom: 2011,
    yearTo: 2024,
    sourceCount: 9,
  },
  {
    id: "peace-narrative",
    slug: "peace-narrative",
    name: "Peace Narrative",
    category: "Ukraine War",
    overview:
      "A framing that positions Russia's invasion of Ukraine as a defensive or peace-seeking action, while portraying Western military aid as escalation. Amplified through diplomatic channels, state media, and sympathetic political actors across Europe.",
    countries: [
      nc("RU", 1),
      nc("BY", 0.9),
      nc("DE", 0.55),
      nc("FR", 0.5),
      nc("IT", 0.45),
      nc("HU", 0.75),
      nc("RS", 0.6),
    ],
    parties: [
      pp("United Russia", "RU"),
      pp("Belaya Rus", "BY"),
      pp("Sahra Wagenknecht Alliance (BSW)", "DE"),
      pp("National Rally", "FR"),
      pp("Five Star Movement", "IT"),
      pp("Fidesz", "HU"),
      pp("Serbian Progressive Party", "RS"),
    ],
    accentColor: "#7BA3BC",
    timeline: [
      { year: 2022, label: "Full-scale invasion launched; 'special operation' framing" },
      { year: 2022, label: "Peace rallies organised in Berlin and Rome" },
      { year: 2023, label: "Orbán blocks EU Ukraine aid package" },
      { year: 2024, label: "Slovak election brings peace-talks rhetoric to government" },
    ],
    actors: [
      "Russian Ministry of Foreign Affairs",
      "AfD and Sahra Wagenknecht Alliance",
      "Fidesz government",
      "Serbian Progressive Party",
    ],
    keywords: [
      "peace talks",
      "escalation",
      "NATO expansion",
      "special operation",
      "ceasefire",
    ],
    relatedIds: ["nato-provocation", "anti-west", "sovereignty"],
    yearFrom: 2022,
    yearTo: 2024,
    sourceCount: 7,
  },
  {
    id: "nato-provocation",
    slug: "nato-provocation",
    name: "NATO Provocation",
    category: "Ukraine War",
    overview:
      "A geopolitical narrative attributing European insecurity to NATO enlargement and Western military presence rather than Russian aggression. Used to justify territorial claims, oppose defence spending, and fracture transatlantic solidarity.",
    countries: [
      nc("RU", 1),
      nc("BY", 0.9),
      nc("RS", 0.65),
      nc("HU", 0.7),
      nc("CN", 0.55),
      nc("TR", 0.45),
      nc("DE", 0.4),
    ],
    parties: [
      pp("United Russia", "RU"),
      pp("Communist Party of the Russian Federation", "RU"),
      pp("Belaya Rus", "BY"),
      pp("Serbian Progressive Party", "RS"),
      pp("Fidesz", "HU"),
      pp("Communist Party of China", "CN"),
      pp("Homeland Party (Vatan)", "TR"),
      pp("Alternative for Germany (AfD)", "DE"),
    ],
    accentColor: "#7BA3BC",
    timeline: [
      { year: 2014, label: "Crimea annexation accompanied by NATO-blame rhetoric" },
      { year: 2018, label: "Putin interviews stress broken promises narrative" },
      { year: 2022, label: "Invasion justified as response to NATO encirclement" },
      { year: 2024, label: "Orbán links EU defence policy to escalation risk" },
    ],
    actors: [
      "Kremlin strategic communications",
      "Serbian defence ministry",
      "Alternative left and right parties",
      "Chinese state media (European editions)",
    ],
    keywords: [
      "NATO expansion",
      "encirclement",
      "provocation",
      "security guarantees",
      "Minsk agreements",
    ],
    relatedIds: ["peace-narrative", "anti-west", "sovereignty"],
    yearFrom: 2014,
    yearTo: 2024,
    sourceCount: 7,
  },
  {
    id: "anti-west",
    slug: "anti-west",
    name: "Anti-West",
    category: "Geopolitics",
    overview:
      "A broad civilisational narrative positioning the West as decadent, imperial, and hostile to alternative political models. Serves as an umbrella frame linking decolonisation rhetoric, multipolarity advocacy, and opposition to US/EU leadership.",
    countries: [
      nc("RU", 1),
      nc("BY", 0.85),
      nc("CN", 0.7),
      nc("IR", 0.65),
      nc("RS", 0.6),
      nc("HU", 0.55),
      nc("TR", 0.5),
      nc("SA", 0.45),
    ],
    parties: [
      pp("United Russia", "RU"),
      pp("Belaya Rus", "BY"),
      pp("Communist Party of China", "CN"),
      pp("Front of Islamic Revolution Stability", "IR"),
      pp("Serbian Progressive Party", "RS"),
      pp("Fidesz", "HU"),
      pp("Justice and Development Party (AKP)", "TR"),
    ],
    accentColor: "#9B6B6B",
    timeline: [
      { year: 2008, label: "Russia-Georgia war reframed as Western proxy conflict" },
      { year: 2014, label: "Multipolar world discourse intensifies post-Crimea" },
      { year: 2022, label: "Sanctions war accelerates anti-Western alignment" },
      { year: 2024, label: "BRICS expansion cited as proof of Western decline" },
    ],
    actors: [
      "Kremlin foreign policy establishment",
      "State media (RT, Sputnik)",
      "Iranian and Chinese diplomatic corps",
      "Anti-imperialist intellectual networks",
    ],
    keywords: [
      "anti-Western",
      "multipolarity",
      "decolonisation",
      "US hegemony",
      "civilisational clash",
    ],
    relatedIds: ["nato-provocation", "global-elites", "peace-narrative"],
    yearFrom: 2008,
    yearTo: 2024,
    sourceCount: 8,
  },
  {
    id: "national-identity",
    slug: "national-identity",
    name: "National Identity",
    category: "Populism",
    overview:
      "A narrative emphasising ethnic or cultural homogeneity as the foundation of legitimate statehood. Invoked to restrict minority rights, resist immigration, and challenge multicultural or federal models of citizenship across Europe.",
    countries: [
      nc("PL", 0.8),
      nc("HU", 0.85),
      nc("FR", 0.75),
      nc("IT", 0.7),
      nc("ES", 0.55),
      nc("GR", 0.5),
      nc("TR", 0.6),
      nc("RS", 0.45),
    ],
    parties: [
      pp("Law and Justice (PiS)", "PL"),
      pp("Fidesz", "HU"),
      pp("National Rally", "FR"),
      pp("Brothers of Italy", "IT"),
      pp("Vox", "ES"),
      pp("Greek Solution", "GR"),
      pp("Nationalist Movement Party (MHP)", "TR"),
      pp("Serbian Radical Party", "RS"),
    ],
    accentColor: "#C4A265",
    timeline: [
      { year: 2010, label: "Orbán declares 'illiberal democracy' rooted in nation" },
      { year: 2015, label: "Migration crisis triggers identity mobilisation" },
      { year: 2019, label: "National-populist gains in European Parliament elections" },
      { year: 2023, label: "Identity politics central to multiple election campaigns" },
    ],
    actors: [
      "National-populist parties",
      "Cultural heritage institutions",
      "Tabloid press",
      "Veterans and patriotic associations",
    ],
    keywords: [
      "national identity",
      "ethnonationalism",
      "assimilation",
      "heritage",
      "citizenship",
    ],
    relatedIds: ["sovereignty", "great-replacement", "traditional-values"],
    yearFrom: 2010,
    yearTo: 2024,
    sourceCount: 8,
  },
  {
    id: "global-elites",
    slug: "global-elites",
    name: "Global Elites",
    category: "Conspiracy",
    overview:
      "A conspiratorial frame attributing political and economic crises to coordinated action by transnational elites — Davos, George Soros, the World Economic Forum. Bridges left and right anti-establishment movements and feeds distrust in democratic institutions.",
    countries: [
      nc("RU", 0.7),
      nc("HU", 0.9),
      nc("PL", 0.55),
      nc("IT", 0.5),
      nc("FR", 0.45),
      nc("US", 0.65),
      nc("DE", 0.4),
    ],
    parties: [
      pp("United Russia", "RU"),
      pp("Fidesz", "HU"),
      pp("Confederation", "PL"),
      pp("League", "IT"),
      pp("Reconquête", "FR"),
      pp("Republican Party", "US"),
      pp("Alternative for Germany (AfD)", "DE"),
    ],
    accentColor: "#C4A265",
    timeline: [
      { year: 2015, label: "Soros conspiracy enters Hungarian government campaigns" },
      { year: 2020, label: "Great Reset theory spreads during COVID-19 pandemic" },
      { year: 2022, label: "WEF named in cost-of-living protest rhetoric" },
      { year: 2024, label: "Elite conspiracy frames merge with election disinformation" },
    ],
    actors: [
      "Orbán anti-Soros campaigns",
      "Alternative media (Telegram, Rumble)",
      "QAnon-adjacent influencers",
      "Russian disinformation outlets",
    ],
    keywords: [
      "global elites",
      "George Soros",
      "World Economic Forum",
      "Great Reset",
      "deep state",
    ],
    relatedIds: ["great-replacement", "anti-west", "liberal-dictatorship"],
    yearFrom: 2015,
    yearTo: 2024,
    sourceCount: 7,
  },
];

export function getNarrativeBySlug(slug: string): Narrative | undefined {
  return narratives.find((narrative) => narrative.slug === slug);
}

export function getRelatedNarratives(id: string): Narrative[] {
  const narrative = narratives.find((entry) => entry.id === id);
  if (!narrative) return [];

  return narrative.relatedIds
    .map((relatedId) => narratives.find((entry) => entry.id === relatedId))
    .filter((entry): entry is Narrative => entry !== undefined);
}
